//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommonFramework.Test.Oracle
{
    using System;
    using System.Collections.Generic;
    
    public partial class RPT01_CAC
    {
        public string REPORTID { get; set; }
        public string OBCC { get; set; }
        public string ODATE { get; set; }
        public string OTIME { get; set; }
        public string VTIME { get; set; }
        public System.DateTime RECEIVETIME { get; set; }
        public System.DateTime INSERTTIME { get; set; }
        public string TT { get; set; }
        public string AA { get; set; }
        public string KK { get; set; }
        public string CCCC { get; set; }
        public string HEADDATE { get; set; }
        public string HEADTIME { get; set; }
        public string BBB { get; set; }
        public string RPTCONTENT { get; set; }
        public bool RPTSTATE { get; set; }
        public System.DateTime REFTIME { get; set; }
    }
}
